import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ErrorWrapper } from "./error-wrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial- CodeEvolution",
    template: "%s | odeEvolution",
  },
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem"
          }}
        >
          <p>header</p>
        </header>
        <ErrorWrapper>
          {children}
        </ErrorWrapper>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem"
          }}  
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
