"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import "./styles.css";
// import "./globals.css";


const navLikns = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forgot-password" }
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [input, setInput] = useState("");
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div>
          <div>
            <input value={input} onChange={(e)=> setInput(e.target.value)}/>
          </div>
          {navLikns.map((link) => {
            const isActive = pathname === link.href || (pathname.startsWith(link.href) && link.href !== "/");
            return (
              <Link className={ isActive ? "font-bold mr-4": "text-blue-500 mr-4"} href={link.href} key={link.name}>
                {link.name}
              </Link>
            )
          })}
        </div>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem"
          }}  
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
